name: "Sync Fork"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync fork"
        shell: bash
        run: gh repo sync ${{ github.repository }} --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_DEBUG: 1
