name: "Sync Fork"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Sync fork"
        shell: bash
        run: gh repo sync ${{ github.repository }} --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_DEBUG: 1
